### PR TITLE
add PrintAndLogEx()

### PR DESCRIPTION
**Pull request by brianpow**
Hi. Still not sure if it is good to include __FILE__, __LINE__ and __FUNCTION__ in the parameters.
Just look at some messages, [!] seems to be error, but not too sure if [+] and [-] means info or other things?

### CODE REVIEW

**Comment by iceman1001** [comment]
I start with a three level information feedback to user.  

[+] positive info
[-] negative info,  not error
[!] error,  function failed, ..

**Comment by iceman1001** [comment]
And what are you using filename, lineno, and function for ?

**Comment by brianpow** [comment]
Most likely for printing debug message (not implemented currently), not sure if it is absolutely needed.

**Comment by iceman1001** [comment]
nay,  skip it.  keep it simple.

**Pull request merged**
