### PR TITLE
Fix bad invocation to bash

### PR DESCRIPTION
**Pull request by hsanjuan**

### CODE REVIEW

**Comment by iceman1001** [comment]
The RRG repo  https://github.com/RfidResearchGroup/proxmark3   has all latest updates based on iceman fork.   It also has a better fix for this.

**Comment by hsanjuan** [comment]
@iceman1001 does the RRG repo work with proxmark3 devices that are not RDV40 (mine :( )?

**Comment by iceman1001** [comment]
just adjust the Makefiles.  

Remove/ Comment out  these from Makefiles and you be fine
			 -DWITH_FLASH \
			 -DWITH_SMARTCARD \
			 -DWITH_FPC \

**Comment by hsanjuan** [comment]
Thanks, OK I updated this PR to use the same fix from RRG in case you want it too. I will work with the RRG repo directly in the future. It feels bad that these repos are not just branches from a single one. It's horrible to port fixes from one to others.

**Comment by iceman1001** [comment]
great!

**Pull request merged**
