### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by egon2**
Dockerfile and Travis CI build

### CODE REVIEW

**Comment by iceman1001** [comment]
Your PR breaks in TravisCI,  ref: https://travis-ci.org/iceman1001/proxmark3/jobs/208471160

Not sure why you want to try an compile in the docker container, since its based upon Ubuntu 14.04, and is covered by current config of TravisCI, which is to compile on ubuntu 14.04.

**Comment by egon2** [comment]
Merging this PR would require setting `DOCKER_USERNAME` and `DOCKER_PASSWORD` environment variables in Travis settings. It pushes produced Docker Image to hub under name `${DOCKER_USERNAME}/proxmark3` and is available to pull.

**Comment by iceman1001** [comment]
I see,  this PR has some potential.   Interesting idea to get the build pushed to dockerhub direct.

**Comment by iceman1001** [comment]
This still breaks in Travis.  
I'll see if I can add my dockerfile, which I use to create my current docker image.

**Pull request closed without merging**
