### PR TITLE
Improved Mifare Plus Atack (hf mf hardnested)

### PR DESCRIPTION
**Pull request by matrix**

### CODE REVIEW

**Comment by iceman1001** [comment]
Thank you for your contribution! 
Is the filehandle = NULL important to for stablity ? or is it your rdv1.0 that needs it?

**Comment by iceman1001** [comment]
I'm getting  "out of memory",  row 1192 in cmdhfmfhard.c,  looks like the malloc fails..
mem leak somewhere?

**Comment by matrix** [comment]
Never happened for me but yes, there's a lot of leaks somewhere to solve.
Try with valgrind :)

**Comment by matrix** [comment]
without file handle old proxmark version crash (segfault) if you press the
reset button

**Comment by matrix** [comment]
It's reproducible? Never happened.
It's a simple if on malloc, look strange

**Comment by iceman1001** [comment]
Filehandle:
its that I think the call to free should do a  filehandle = NULL inside of itself.  Nevermind its not much to add all over the place :)
Mem:
well, never touched the valgrind, but I get a lot of crashes with it when I run the pm3 client.  I think it has to do with being compile with -o2 / -o3  .  I will test with optimisation -o1 or something and run valgrind again.

**Pull request merged**
