### PR TITLE
Added DES AUTH command support

### PR DESCRIPTION
**Pull request by bforbort**
I've developed this code using a blank DESFire v1.4 card, and was able to test it by changing the PICC master key to a new value.  I was drunk when I wrote this so it works but it might not be pretty.  This code only adds single DES support to the auth command, so remember to make the last 8 bits of a new key the same as the first 8 bits, otherwise the command will fail when you try to auth with the new key.  I have yet to test this command on a card that has been set to 3DES operation.  I assume it will fail but I do not know or care where it will fail right now, I'm just way to drunk to add anything more.

### CODE REVIEW

**Comment by iceman1001** [comment]
Sweet bforbort! 
It's a good start at least. I can't verify it since I don't have a blank DESFIRE tag.  
When you mention the 8bits, did you mean the rotateleft operation on the new key.

**Comment by bforbort** [comment]
If you privately email me a mailing address, I can send you a couple blank DESFire cards.  They will have to the Master Key '00 00 00 00 00 00 00 00'

Referring to page 15 of the DESFire MF3 IC D40 data sheet, you will find that both DES and 3DES keys are stored in strings consisting of 16 bits on the DESFire card.  If the 2nd half of the key string is equal to the 1st half, the key is handled as a single DES key by the PICC.

In my code, I've used the example code '00 11 22 33 44 55 66 77 00 11 22 33 44 55 66 77.' This would be the 16 bit representation of the 8 bit single DES key '00 11 22 33 44 55 66 77.'

**Comment by iceman1001** [comment]
You are right, I remember to have read about DES/3DES before. I got confused by you mention bits, instead of bytes.  It was a while since I did something with desfire and when I did it was most AES.

**Comment by iceman1001** [comment]
Btw, I can't find your email address.

**Comment by bforbort** [comment]
b.forbort@gmail.com

**Pull request merged**
