### PR TITLE
Fixes for compiling on Android

### PR DESCRIPTION
**Pull request by angelsl**
Minor fixes to get the code to compile on Android.

### CODE REVIEW

**Comment by iceman1001** [comment]
Sweet work in getting it to compile on Android. 
I'm curious about **__atomic_fetch_add vs __sync_fetch_and_add**
is there any penalty in time using your atomic version?  Or is it as fast?

**Comment by angelsl** [comment]
@iceman1001

It should be on par or better, because __atomic intrinsics are meant to replace the __sync intrinsics.

**Comment by iceman1001** [comment]
@aczid also added it to his main code.  @angelsl  you must tell us how it works on android!

**Comment by angelsl** [comment]
@iceman1001 I'm working on an app for it. Basically I'm replacing proxmark3.c and ui.c with some glue code for a normal Java Android app to the client code as a JNI library to interface with the proxmark3 device.

I just got the code in proxmark3/client to compile with the NDK yesterday; you can check out my progress [here](https://github.com/angelsl/adr-proxmark3).

**Pull request merged**
