### PR TITLE
Fix crashes on amd systems when compiled with a intel cpu

### PR DESCRIPTION
**Pull request by Gator96100**
Fixes client crashes on start when compiled on an intel platform and run on a amd system.

### CODE REVIEW

**Review by iceman1001 — CHANGES_REQUESTED** [review]
-march=native is needed for the hardnested BF solver if I remember it correct.

**Comment by Gator96100** [comment]
I did test the hardnested command and everything seems to work on Windows as well as Linux even without -march=native.

**Comment by iceman1001** [comment]
...did you test execution time difference ?

**Comment by iceman1001** [comment]
I guess the crashes comes from ppl downloading your intel-compiled client and try running it on AMD..
The -march=native should optimise code for each CPU / chipset it was compiled on.

Hard to please everyone I guess

**Pull request closed without merging**
