### PR TITLE
Added zero-padding option to dumptoemul-mfu script

### PR DESCRIPTION
**Pull request by bogiton**

### CODE REVIEW

**Review by iceman1001 — COMMENTED** [review]
Nice one,
but I'm not sure of this is the best way to go.   With a -p...
I think its just better to automatically pad the file,   or the more complicated way of identifying the card...

Make a version which auto-pad and writes message about it...  that I will merge

**Comment by iceman1001** [comment]
Different solution.
https://github.com/iceman1001/proxmark3/commit/73a5e3b23d4387a9570e29d09ac197d171920fd2

**Comment by bogiton** [comment]
Ah, and I just updated the lua script to automatically add missing blocks up to 255:
https://github.com/bogiton/proxmark3/blob/master/client/scripts/dumptoemul-mfu.lua
Your solution seems better though.

**Comment by iceman1001** [comment]
Try it out. And see if it works as u expect.

**Pull request closed without merging**
