### PR TITLE
Updated the update.sh script

### PR DESCRIPTION
**Pull request by joanbono**
Now the `update.sh` script works both in Linux and macOS as commented by Tom in #226

### CODE REVIEW

**Comment by iceman1001** [comment]
Sweet!

A solution that doesn't demand two scripts is a good one.

don't forget to make an entry in changelog.md file.

**Comment by TomHarkness** [comment]
Very very nice!

**Comment by TomHarkness** [comment]
I will copy this in to my RDV4 fork and merge to master as no one has done that yet.

**Comment by joanbono** [comment]
Hi @iceman1001 Should I open a new PR with the Changelog modified?

**Comment by iceman1001** [comment]
@joanbono  go ahead and do that.

**Pull request merged**
