### PR TITLE
Adding a 'recoverpw' command for T55xx to try to recover corrupt pass…

### PR DESCRIPTION
**Pull request by alexgrin**
…word written by a handheld cloner by fiddling with bits in the expected password.

### CODE REVIEW

**Comment by iceman1001** [comment]
Thanks!
I really this one. It brings added value to the PM3 device.  
A suggestion is that you also take one password as input to recoverpwd,  this will enable it to deal with more than that hardcoded clone pwd :)

Keep up the good work.

**Comment by alexgrin** [comment]
It already does that :) If no password is specified, it will use the one that's commonly used by many Chinese cloners.

**Comment by iceman1001** [comment]
sorry, you are totally right here.  I forgot that it is the default value returned :)

**Comment by iceman1001** [comment]
the other known cloner pwd is in the default_keys.dic file in the top.

**Comment by alexgrin** [comment]
Oh, good to know!

**Comment by iceman1001** [comment]
And now I'm wrong again,  its in the default_pwd.dic file.

**Comment by alexgrin** [comment]
I see! My random locked device had a password of 51253648 - one bit off 51243648 in the dict file.

**Comment by iceman1001** [comment]
Have you seen that behavior on more tags used on the handheld cloner?

**Comment by alexgrin** [comment]
I have not seen the failures personally because I refuse to use handheld cloner on my implant, but there's anecdotal evidence of handheld cloners corrupting the xEM implants so after considering what could have gone wrong, bit flipping and incomplete writes seem likely, hence this code. I suppose my HID cloned card experienced that failure and I got lucky with discovering it.

**Comment by iceman1001** [comment]
Great find,  the t55x7 communication is easy to get wrong as we have noticed with the pm3 reworking its code.  At least now its very stable giving solid readouts.

**Pull request merged**
